version: "3.9"
networks:
    laravel:

services:
    nginx:
        image: nginx:stable
        container_name: nginx_todo_app
        ports:
            - 8000:80
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "2"
                    memory: 2048M
        volumes:
            - ./:/var/www:delegated
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - laravel
    mysql:
        image: mysql:8
        container_name: mysql_todo_app
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php_todo_app
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - ./vendor:/var/www/vendor:cached
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: 4096M
                reservations:
                    cpus: "2"
                    memory: 2048M
        networks:
            - laravel
